# HEADY_BRAND:BEGIN
# ╔══════════════════════════════════════════════════════════════════╗
# ║  █╗  █╗███████╗ █████╗ ██████╗ █╗   █╗                     ║
# ║  █║  █║█╔════╝█╔══█╗█╔══█╗╚█╗ █╔╝                     ║
# ║  ███████║█████╗  ███████║█║  █║ ╚████╔╝                      ║
# ║  █╔══█║█╔══╝  █╔══█║█║  █║  ╚█╔╝                       ║
# ║  █║  █║███████╗█║  █║██████╔╝   █║                        ║
# ║  ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝    ╚═╝                        ║
# ║                                                                  ║
# ║  ∞ SACRED GEOMETRY ∞  Organic Systems · Breathing Interfaces    ║
# ║  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  ║
# ║  FILE: scripts/docker-mcp-setup.ps1                               ║
# ║  LAYER: root                                                      ║
# ╚══════════════════════════════════════════════════════════════════╝
# HEADY_BRAND:END

param(
    [string]$McpConfigPath = ".\mcp_config.json",
    [switch]$Force = $false,
    [string]$DockerComposeFile = "docker-compose.mcp.yml"
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

function Write-HeadyLog {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    Write-Host "[$timestamp] [$Level] $Message" -ForegroundColor Cyan
}

function Test-DockerInstalled {
    try {
        $dockerVersion = docker --version
        Write-HeadyLog "Docker found: $dockerVersion"
        return $true
    }
    catch {
        Write-HeadyLog "Docker not found. Please install Docker Desktop." "ERROR"
        return $false
    }
}

function Test-DockerRunning {
    try {
        docker ps > $null 2>&1
        Write-HeadyLog "Docker daemon is running"
        return $true
    }
    catch {
        Write-HeadyLog "Docker daemon is not running. Starting Docker Desktop..." "WARN"
        Start-Process "C:\Program Files\Docker\Docker\Docker Desktop.exe" -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 10
        
        for ($i = 0; $i -lt 30; $i++) {
            try {
                docker ps > $null 2>&1
                Write-HeadyLog "Docker daemon is now running"
                return $true
            }
            catch {
                Start-Sleep -Seconds 2
            }
        }
        Write-HeadyLog "Docker daemon failed to start" "ERROR"
        return $false
    }
}

function Test-DockerCompose {
    try {
        $composeVersion = docker-compose --version
        Write-HeadyLog "Docker Compose found: $composeVersion"
        return $true
    }
    catch {
        Write-HeadyLog "Docker Compose not found. Installing..." "WARN"
        try {
            docker run --rm -v /var/run/docker.sock:/var/run/docker.sock docker/compose:latest --version
            Write-HeadyLog "Docker Compose available via docker compose"
            return $true
        }
        catch {
            Write-HeadyLog "Docker Compose installation failed" "ERROR"
            return $false
        }
    }
}

function Initialize-McpNetwork {
    Write-HeadyLog "Initializing MCP network..."
    
    $networkExists = docker network ls --filter "name=mcp-network" --quiet
    if ($networkExists) {
        Write-HeadyLog "MCP network already exists"
    }
    else {
        docker network create mcp-network --driver bridge
        Write-HeadyLog "Created MCP network"
    }
}

function Initialize-McpData {
    Write-HeadyLog "Initializing MCP data directories..."
    
    $mcpDataPath = ".\mcp-data"
    if (-not (Test-Path $mcpDataPath)) {
        New-Item -ItemType Directory -Path $mcpDataPath -Force | Out-Null
        Write-HeadyLog "Created mcp-data directory"
    }
}

function Create-EnvFile {
    Write-HeadyLog "Creating .env file for Docker MCP..."
    
    $envContent = @"
# HEADY SYSTEMS :: DOCKER MCP ENVIRONMENT CONFIGURATION
# Generated by docker-mcp-setup.ps1

# Docker Configuration
DOCKER_HOST=unix:///var/run/docker.sock
DOCKER_BUILDKIT=1
COMPOSE_DOCKER_CLI_BUILD=1

# Database Configuration
DATABASE_URL=postgresql://postgres:password@postgres:5432/heady
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=heady
POSTGRES_USER=postgres
POSTGRES_PASSWORD=password

# Redis Configuration
REDIS_HOST=redis
REDIS_PORT=6379

# MCP Services Configuration
NODE_ENV=production
MCP_FILESYSTEM_PATH=/workspace
MCP_MEMORY_STORAGE_PATH=/data

# Cloudflare Integration (optional)
# COPILOT_MCP_CLOUDFLARE_API_TOKEN=your_token_here
# COPILOT_MCP_CLOUDFLARE_ACCOUNT_ID=your_account_id_here

# Kubernetes (optional)
# KUBECONFIG=/path/to/kubeconfig

# Monitoring
MONITORING_INTERVAL=30
METRICS_RETENTION=24h
"@

    if ((Test-Path ".env") -and -not $Force) {
        Write-HeadyLog ".env file already exists. Use -Force to overwrite." "WARN"
    }
    else {
        Set-Content -Path ".env" -Value $envContent
        Write-HeadyLog "Created .env file"
    }
}

function Create-InitSql {
    Write-HeadyLog "Creating database initialization script..."
    
    $initSqlContent = @"
-- HEADY SYSTEMS :: DATABASE INITIALIZATION
-- Created by docker-mcp-setup.ps1

-- Create extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- Create schemas
CREATE SCHEMA IF NOT EXISTS heady;
CREATE SCHEMA IF NOT EXISTS mcp;

-- Create MCP state table
CREATE TABLE IF NOT EXISTS mcp.state (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    key VARCHAR(255) NOT NULL UNIQUE,
    value JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create MCP logs table
CREATE TABLE IF NOT EXISTS mcp.logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    service VARCHAR(255) NOT NULL,
    level VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    context JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_mcp_state_key ON mcp.state(key);
CREATE INDEX IF NOT EXISTS idx_mcp_logs_service ON mcp.logs(service);
CREATE INDEX IF NOT EXISTS idx_mcp_logs_created_at ON mcp.logs(created_at DESC);

-- Create heady schema tables
CREATE TABLE IF NOT EXISTS heady.projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS heady.checkpoints (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID REFERENCES heady.projects(id),
    checkpoint_data JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for heady schema
CREATE INDEX IF NOT EXISTS idx_heady_projects_status ON heady.projects(status);
CREATE INDEX IF NOT EXISTS idx_heady_checkpoints_project_id ON heady.checkpoints(project_id);

-- Grant permissions
GRANT USAGE ON SCHEMA heady TO postgres;
GRANT USAGE ON SCHEMA mcp TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA heady TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA mcp TO postgres;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA heady TO postgres;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA mcp TO postgres;
"@

    if ((Test-Path "init.sql") -and -not $Force) {
        Write-HeadyLog "init.sql already exists. Use -Force to overwrite." "WARN"
    }
    else {
        Set-Content -Path "init.sql" -Value $initSqlContent
        Write-HeadyLog "Created init.sql"
    }
}

function Create-McpConfig {
    Write-HeadyLog "Creating MCP configuration..."
    
    $mcpConfig = @{
        version = "1.0"
        services = @{
            filesystem = @{
                type = "mcp"
                image = "node:18-alpine"
                command = "npx -y @modelcontextprotocol/server-filesystem /workspace"
                volumes = @("/workspace", "/app/node_modules")
                environment = @{
                    NODE_ENV = "production"
                }
            }
            postgres = @{
                type = "mcp"
                image = "node:18-alpine"
                command = "npx -y @modelcontextprotocol/server-postgres"
                environment = @{
                    DATABASE_URL = "postgresql://postgres:password@postgres:5432/heady"
                    NODE_ENV = "production"
                }
            }
            memory = @{
                type = "mcp"
                image = "node:18-alpine"
                command = "npx -y @modelcontextprotocol/server-memory"
                volumes = @("/data", "/app/node_modules")
                environment = @{
                    NODE_ENV = "production"
                    MEMORY_STORAGE_PATH = "/data"
                }
            }
            fetch = @{
                type = "mcp"
                image = "node:18-alpine"
                command = "npx -y @modelcontextprotocol/server-fetch"
                environment = @{
                    NODE_ENV = "production"
                }
            }
        }
        databases = @{
            postgres = @{
                image = "postgres:15-alpine"
                environment = @{
                    POSTGRES_DB = "heady"
                    POSTGRES_USER = "postgres"
                    POSTGRES_PASSWORD = "password"
                }
                ports = @("5432:5432")
            }
            redis = @{
                image = "redis:7-alpine"
                ports = @("6379:6379")
            }
        }
    }
    
    $mcpConfig | ConvertTo-Json -Depth 10 | Set-Content -Path $McpConfigPath
    Write-HeadyLog "Created MCP configuration at $McpConfigPath"
}

function Validate-DockerCompose {
    Write-HeadyLog "Validating docker-compose.mcp.yml..."
    
    if (-not (Test-Path $DockerComposeFile)) {
        Write-HeadyLog "docker-compose.mcp.yml not found" "ERROR"
        return $false
    }
    
    try {
        docker-compose -f $DockerComposeFile config > $null 2>&1
        Write-HeadyLog "docker-compose.mcp.yml is valid"
        return $true
    }
    catch {
        Write-HeadyLog "docker-compose.mcp.yml validation failed: $_" "ERROR"
        return $false
    }
}

function Main {
    Write-HeadyLog "=== Docker MCP Setup for HeadySystems ==="
    
    if (-not (Test-DockerInstalled)) {
        exit 1
    }
    
    if (-not (Test-DockerRunning)) {
        exit 1
    }
    
    if (-not (Test-DockerCompose)) {
        exit 1
    }
    
    Initialize-McpNetwork
    Initialize-McpData
    Create-EnvFile
    Create-InitSql
    Create-McpConfig
    
    if (-not (Validate-DockerCompose)) {
        exit 1
    }
    
    Write-HeadyLog "=== Docker MCP Setup Complete ==="
    Write-HeadyLog "Next steps:"
    Write-HeadyLog "1. Review .env file and update credentials if needed"
    Write-HeadyLog "2. Run: .\scripts\start-docker-mcp.ps1"
    Write-HeadyLog "3. Verify services: docker-compose -f docker-compose.mcp.yml ps"
}

Main
